dist: trusty
sudo: required
language: minimal
addons:
  apt:
    packages:
      - qemu-utils
script:
  - sudo ./alpine-make-vm-image
        --image-format qcow2
        --image-size 2G
        --repositories-file example/repositories
        --keys-dir example/keys
        --packages "$(cat example/packages)"
        --script-chroot
        alpine-virthardened-$(date +%Y-%m-%d).qcow2 -- ./example/configure.sh
#deploy:
#  provider: releases
#  api_key:
#    secure: <Encrypted GitHub Personal Token>
#  file: "*.qcow2"
#  file_glob: true
#  skip_cleanup: true
#  on:
#    tags: true
